### ISSUE TITLE
Oauth does not work

### ISSUE THREAD

**Issue by jjwp** [dashedstripes/zendesk-node-api#14]
I have set `oauth: true` in my setup and the response returned is always 'Couldn\'t authenticate you'.
Checked your code and it doesn't look like the oauth flag is checked. Is it possible to create a ticket using oauth with this package?

**Comment by glrodasz** [comment]
@jjwp Are you using a token from Zendesks or an Access Token following the OAuth flow here: https://support.zendesk.com/hc/en-us/articles/203663836-Using-OAuth-authentication-with-your-application?

**Comment by jjwp** [comment]
Thanks for your reply @glrodasz, I have been following this flow: https://help.zendesk.com/hc/en-us/articles/115002036967 and passing the `full_token`

**Comment by glrodasz** [comment]
@jjwp It is used here: https://github.com/dashedstripes/zendesk-node-api/blob/master/src/zendesk.js#L4 Have you tried the CURL requests with your token in order to discard if is an issue with the token?

**Comment by jjwp** [comment]
ahhhh, I don't have that `if` statement in my version. I downloaded your package via npm, are the versions out of sync?

**Comment by glrodasz** [comment]
@jjwp Well, I'm not sure if they are out of sync. Let's wait for the author review. Meanwhile, you could add the repo version instead in your `package.json` http://stackoverflow.com/a/17509764

**Comment by jjwp** [comment]
Great, thanks for your help @glrodasz 👍
